import type { Profile } from "./types";

export const demoViewer: Profile = {
  id: "demo-viewer",
  username: "nara",
  fullName: "Nara Putri",
  age: 22,
  city: "Bandung",
  country: "Indonesia",
  mbti: "INFP",
  languages: ["Indonesia", "English"],
  hobbies: ["Journaling", "Cafe hopping", "Fotografi"],
  interests: ["Indie music", "Film", "Psikologi", "Kucing"],
  lookingFor: ["Teman baru", "Study buddy"],
  bio: "Anak visual yang suka percakapan panjang, toko buku kecil, dan playlist yang dibuat terlalu serius.",
  photoUrl: "/people/nara.svg",
};

export const sampleProfiles: Profile[] = [
  {
    id: "demo-bima",
    username: "bimaworks",
    fullName: "Bima Ardhana",
    age: 23,
    city: "Jakarta",
    country: "Indonesia",
    mbti: "ENFJ",
    languages: ["Indonesia", "English"],
    hobbies: ["Basket", "Ngopi", "Volunteer"],
    interests: ["Film", "Psikologi", "Indie music", "Travel"],
    lookingFor: ["Teman baru", "Project buddy"],
    bio: "People person yang selalu punya rekomendasi tempat makan. Lagi cari teman buat proyek kecil dan eksplor kota.",
    photoUrl: "/people/bima.svg",
    compatibility: 94,
    sharedInterests: ["Film", "Psikologi", "Indie music"],
    isOnline: true,
  },
  {
    id: "demo-keisha",
    username: "keishacodes",
    fullName: "Keisha Aulia",
    age: 21,
    city: "Yogyakarta",
    country: "Indonesia",
    mbti: "INTP",
    languages: ["Indonesia", "English", "Japanese"],
    hobbies: ["Coding", "Anime", "Board game"],
    interests: ["Tech", "Game", "Film", "Japanese"],
    lookingFor: ["Study buddy", "Gaming buddy"],
    bio: "Bisa membahas bug tiga jam, lalu kalah telak di board game. Sedang belajar bahasa Jepang pelan-pelan.",
    photoUrl: "/people/keisha.svg",
    compatibility: 88,
    sharedInterests: ["Film"],
    isOnline: false,
  },
  {
    id: "demo-raka",
    username: "rakawanders",
    fullName: "Raka Pradipta",
    age: 25,
    city: "Surabaya",
    country: "Indonesia",
    mbti: "ENTP",
    languages: ["Indonesia", "English"],
    hobbies: ["Lari", "Street photo", "Podcast"],
    interests: ["Fotografi", "Startup", "Jazz", "Travel"],
    lookingFor: ["Teman baru", "Running buddy"],
    bio: "Suka ide random, jalan kaki tanpa tujuan, dan memotret kota sebelum matahari benar-benar bangun.",
    photoUrl: "/people/raka.svg",
    compatibility: 82,
    sharedInterests: ["Fotografi"],
    isOnline: true,
  },
  {
    id: "demo-salva",
    username: "salvareads",
    fullName: "Salva Nirmala",
    age: 24,
    city: "Malang",
    country: "Indonesia",
    mbti: "INFJ",
    languages: ["Indonesia", "English", "Korean"],
    hobbies: ["Membaca", "Baking", "Pilates"],
    interests: ["Buku", "Film", "K-pop", "Psikologi"],
    lookingFor: ["Teman baru", "Language exchange"],
    bio: "Pembaca sunyi yang ternyata cerewet kalau sudah membahas buku, film coming-of-age, atau resep cookies.",
    photoUrl: "/people/salva.svg",
    compatibility: 91,
    sharedInterests: ["Film", "Psikologi"],
    isOnline: false,
  },
];

